import { readFileSync } from "node:fs";
import { join } from "node:path";
import { assertContains, assertNotContains } from "../helpers/assertions.mts";
import { TARGET_SPECS } from "../../src/patcher-targets.mts";

export function runGeneratedCliSuite(rootDir: string): void {
  const generatedCli = readFileSync(join(rootDir, "bin", "codexfast"), "utf8");
  assertContains(generatedCli, 'const MIN_NODE_VERSION = "18.12.0";', "expected generated CLI to enforce Node.js 18.12.0 or later");
  assertContains(generatedCli, "runtimePatchReconnectMaxAttempts = 3", "expected generated CLI to bound runtime launch reconnect attempts");
  assertContains(generatedCli, "runtimePatchBrowserConnectTimeoutMs = 15_000", "expected generated CLI to preserve the bounded cold-start connection window");
  assertContains(generatedCli, "reconnectObservationTimeoutMs", "expected generated CLI to enforce a wall-clock reconnect observation deadline");
  assertContains(generatedCli, "reconnectConnectController?.abort()", "expected generated CLI to cancel a pending reconnect during shutdown");
  assertContains(generatedCli, "runtimeRendererOriginFromLocation", "expected generated CLI to resolve an empty target URL from the renderer before reload");
  assertContains(generatedCli, "globalThis.location?.href ?? ''", "expected generated CLI to query the pending renderer location without mutating it");
  assertContains(generatedCli, "!attached.waitingForDebugger && targetOrigin", "expected generated CLI to reload only location-confirmed existing app renderers");
  assertContains(generatedCli, "beginInitialResourcePreload", "expected generated CLI to preload after a pending renderer binds late to an app origin");
  assertContains(generatedCli, "reconnectObservationTasks", "expected generated CLI shutdown to drain reconnect observation tasks");
  assertContains(generatedCli, "initialPreloadHandlers", "expected generated CLI shutdown to drain initial preload handlers");
  assertContains(generatedCli, "drainReconnectObservationTasks", "expected generated CLI shutdown to wait for every reconnect observation task");
  assertContains(generatedCli, "Promise.allSettled", "expected generated CLI shutdown not to stop draining after the first rejected handler");
  assertContains(generatedCli, "await session.close()", "expected generated CLI to await runtime-session cleanup before exit");
  assertContains(generatedCli, '"Browser.getVersion"', "expected generated CLI to heartbeat the browser-level CDP runtime patch session");
  assertContains(generatedCli, '"Target.setAutoAttach"', "expected generated CLI to auto-attach before renderer JavaScript runs");
  assertContains(generatedCli, "waitForDebuggerOnStart: true", "expected generated CLI to pause new renderer targets before JavaScript runs");
  assertContains(generatedCli, '"Runtime.runIfWaitingForDebugger"', "expected generated CLI to resume renderer targets after interception is enabled");
  assertContains(generatedCli, "message.sessionId", "expected generated CLI to route Fetch events through flattened target sessions");
  assertContains(generatedCli, "send(method, params, sessionId)", "expected generated CLI to send CDP commands to flattened target sessions");
  assertContains(generatedCli, "Runtime patch session lost after", "expected generated CLI to report exhausted runtime patch reconnects clearly");
  assertContains(generatedCli, "runtimePatchNoTargetIdleMs", "expected generated CLI to wait for quiet JS traffic before failing initial runtime target discovery");
  assertContains(generatedCli, "app://*/.vite/build/*.js", "expected generated CLI to intercept main-process build assets if Electron serves them through app://");
  assertContains(generatedCli, "codexfastAutomaticUpdateCheck", "expected generated CLI to include the dynamic automatic update main-process hook");
  assertContains(generatedCli, "forcedUpdateScheduleSignature", "expected generated CLI to suppress automatic forced update install scheduling when disableAutomaticUpdates is enabled");
  assertNotContains(generatedCli, "CODEXFAST_DISABLE_AUTOMATIC_UPDATES", "expected generated CLI not to rely on startup-only automatic update environment state");
  assertContains(generatedCli, "disableAutomaticUpdates", "expected generated CLI to include the automatic update setting patches");
  assertContains(generatedCli, "detached: true", "expected runtime launch to isolate Codex from the launch terminal process group");
  assertContains(generatedCli, "child.unref();", "expected runtime launch to let Codex survive when the launcher exits");
  assertContains(generatedCli, "IApplicationActivationManager", "expected generated CLI to activate the Windows MSIX through ApplicationActivationManager");
  assertContains(generatedCli, "tasklist.exe", "expected generated CLI to check ChatGPT.exe/Codex.exe with tasklist on Windows");
  assertContains(generatedCli, "taskkill.exe", "expected generated CLI to terminate only the launched Windows process tree");
  assertContains(generatedCli, '$process.Handle', "expected generated CLI to hold the verified process handle through taskkill");
  assertContains(generatedCli, 'Arguments = "/PID $processId /T /F"', "expected generated CLI to pass the launched PID tree to taskkill");
  assertContains(generatedCli, "CODEXFAST_TERMINATE_START_TIME_UTC", "expected generated CLI to revalidate launched process identity inside the termination helper");
  assertContains(generatedCli, "without this launch's", "expected generated CLI to bind Windows process ownership to the random CDP arguments");
  assertContains(generatedCli, "CODEXFAST_APP_USER_MODEL_ID", "expected generated CLI to support the Windows AUMID override");
  assertContains(generatedCli, "speed-setting-destructured-option-count", "expected generated CLI to include the Windows Settings Fast target");
  assertContains(generatedCli, "speed-service-tier-allowance-26601", "expected generated CLI to include the Windows Fast allowance target");
  assertContains(generatedCli, "speed-service-tier-request-allowance-26707", "expected generated CLI to include the Windows Fast request target");
  assertContains(generatedCli, "speed-service-tier-conversation-fallback-26707", "expected generated CLI to include the Windows Fast conversation fallback target");
  assertContains(generatedCli, "intelligence-speed-menu-options-boolean-code", "expected generated CLI to include the Windows Intelligence Speed target");
  assertContains(generatedCli, "service-tier-slash-command", "expected generated CLI to include the Windows Fast slash-command target");
  assertContains(generatedCli, "gpt5x-model-list-options", "expected generated CLI to include the Windows GPT-5.x model-list target profile");
  assertContains(generatedCli, "gpt56-model-query-selector", "expected generated CLI to include the Windows GPT-5.6 selector target profile");
  assertContains(generatedCli, "Speed service tier request allowance", "expected generated CLI to require the complete Windows Fast label set");
  assertContains(generatedCli, "Fast slash command", "expected generated CLI to require the Windows Fast slash-command label");
  assertContains(generatedCli, "class ReadOnlyAsarArchive", "expected generated CLI to include the self-contained read-only ASAR reader");
  assertContains(generatedCli, "inspectRuntimePatchCompatibility", "expected generated CLI to inspect Windows target signatures dynamically");
  assertContains(generatedCli, "signature-compatible-update", "expected generated CLI to preserve the unlisted Windows compatibility source");
  assertContains(generatedCli, "unlisted registered update", "expected generated CLI to describe unlisted compatibility without implying cryptographic signature validation");
  assertContains(generatedCli, "Could not determine one renderer root", "expected generated CLI to derive runtime resource paths from the inspected ASAR");
  assertContains(generatedCli, "expectedTarget.runtimePath", "expected generated CLI to bind observed targets to discovered runtime paths");
  assertContains(generatedCli, "expectedTarget.contentSha256", "expected generated CLI to bind observed targets to inspected response hashes");
  assertContains(generatedCli, "Inspect Windows compatibility without launching Codex", "expected generated CLI to expose the read-only inspect command");
  assertContains(generatedCli, 'schemaVersion: 1', "expected generated CLI to include the inspect JSON schema");
  assertContains(generatedCli, 'WINDOWS_RUNTIME_COMPATIBILITY_FAILED', "expected generated CLI to report structured compatibility failures");
  assertContains(generatedCli, 'providerConfigurationInspected: false', "expected generated CLI not to claim provider inspection");
  assertNotContains(generatedCli, 'from "./cli-inspect.mts"', "expected generated CLI to inline the inspect module");
  assertNotContains(generatedCli, "general-settings-Dtfq14Yt.js", "expected generated CLI not to hard-code version-specific Windows chunk names");
  assertNotContains(generatedCli, "runtimePatchInitialResourcePathsByWindowsVersion", "expected generated CLI not to use a static Windows version-to-resource table");
  assertContains(generatedCli, "runtimePatchPreloadMaxAttempts = 3", "expected generated CLI to retry transient preload execution-context failures");
  assertContains(generatedCli, "exceptionDetails", "expected generated CLI to surface renderer-side preload failures");
  assertNotContains(generatedCli, "Verb RunAs", "expected generated CLI not to request UAC elevation");
  assertNotContains(generatedCli, "tccutil", "expected generated CLI not to reset macOS ScreenCapture permissions");
  assertNotContains(generatedCli, "ScreenCapture", "expected generated CLI not to contain ScreenCapture reset logic");
  assertNotContains(generatedCli, "codexfast-browser-peer-auth", "expected generated CLI not to contain browser-use native pipe peer-auth compatibility patch");
  assertNotContains(generatedCli, "missing-code-signing-identity", "expected generated CLI not to authorize missing-code-signing-identity peer-auth failures");
  assertNotContains(generatedCli, "__selftest-legacy-", "expected generated CLI not to contain removed legacy file-patch self-tests");
  assertNotContains(generatedCli, "@electron/asar", "expected generated CLI not to contain legacy bundle patch asar tooling");
  assertNotContains(generatedCli, "app.asar1", "expected generated CLI not to contain legacy archive backup handling");
  assertNotContains(generatedCli, "__SUPPORTED_APP_VERSIONS__", "expected generated CLI to inline supported app versions without placeholder names");
  assertNotContains(generatedCli, "__SUPPORTED_WINDOWS_APP_VERSIONS__", "expected generated CLI to inline supported Windows versions without placeholder names");

  const targetIds = TARGET_SPECS.map((spec) => spec.id).join("\n");
  assertContains(targetIds, "speed-setting", "expected patcher target specs to be importable at runtime");
  assertContains(targetIds, "disable-automatic-updates-schema", "expected automatic update setting schema target to be importable at runtime");
  assertContains(targetIds, "disable-automatic-updates-setting", "expected automatic update General setting target to be importable at runtime");
  assertNotContains(
    targetIds,
    "browser-use-native-pipe-peer-auth",
    "expected browser-use native pipe peer-auth compatibility target to be removed",
  );
}
